# Generated by Django 5.0.6 on 2025-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_resume_candidate_resume_candidate_reference_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('HR', 'HR')], max_length=20),
        ),
    ]
